{% set sdk_version = "5.0.301" %}
{% set runtime_version = "5.0.7" %}
#{% set sha256 = "5fa7c6d13e7a0f0b2e0a9bae7086906f5ec4bd8b8ff8ae86ed9fc5506c369715" %}  # [aarch64]
{% set sha256 = "3551215f7723cf9d262374ee3e7b83a4cd3a0ccaa1fa0b5decaf67c0ea054448" %}  # [linux]
{% set sha256 = "c4d1b630e6ff66127bde789edbdef68d83db1b2d647c10a7d25914819606e81f" %}  # [osx]
{% set sha256 = "642686c4109e3659c49c0ef12fa1847f4b7af69f68bf21dbb97726d4ba52a5f1" %}  # [win]
#{% set platform = "linux-arm64" %}    # [aarch64]
{% set platform = "linux-x64" %}  # [linux]
{% set platform = "osx-x64" %}    # [osx]
{% set platform = "win-x64" %}    # [win]
{% set ext = "tar.gz" %}      # [not win]
{% set ext = "zip" %}         # [win]

package:
  name: dotnet
  version: {{ sdk_version }}

source:
  url: https://dotnetcli.azureedge.net/dotnet/Sdk/{{ sdk_version }}/dotnet-sdk-{{ sdk_version }}-{{ platform }}.{{ ext }}
  sha256: {{ sha256 }}
  folder: dotnet

build:
  number: 0 

outputs:
  - name: dotnet
    version: {{ sdk_version }}
    requirements:
      run:
        - {{ pin_subpackage('dotnet-runtime', exact=True) }}
        - {{ pin_subpackage('dotnet-aspnetcore', exact=True) }}
        - {{ pin_subpackage('dotnet-desktop', exact=True) }}  # [win]
        - {{ pin_subpackage('dotnet-sdk', exact=True) }}
    test:
      commands:
       - dotnet --version

  - name: dotnet-runtime
    version: {{ runtime_version }}
    script: build-runtime.bat       # [win]
    script: build-runtime.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
    test:
      commands:
        - dotnet --list-runtimes
    about:
      home: https://github.com/dotnet/runtime
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-sdk
    version: {{ sdk_version }}
    script: build-sdk.bat       # [win]
    script: build-sdk.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust             # [linux64]
        - libcurl               # [unix]
        - icu                   # [unix]
        - krb5                  # [unix]
        - __glibc >=2.17        # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - dotnet --version
    about:
      home: https://github.com/dotnet/sdk
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-aspnetcore
    version: {{ runtime_version }}
    script: build-aspnetcore.bat    # [win]
    script: build-aspnetcore.sh     # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - test -d $PREFIX/lib/dotnet/shared/Microsoft.AspNetCore.App              # [not win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.AspNetCore.App exit 1  # [win]
    about:
      home: https://github.com/dotnet/aspnetcore
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-desktop                                                              # [win]
    version: {{ runtime_version }}                                                    # [win]
    script: build-desktop.bat                                                         # [win]
    requirements:                                                                     # [win]
      build:                                                                          # [win]
        - posix                                                                       # [win]
      run:                                                                            # [win]
        - dotnet-runtime ={{ runtime_version }}                                       # [win]
    test:                                                                             # [win]
      commands:                                                                       # [win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.WindowsDesktop.App exit 1  # [win]
    about:                                                                            # [win]
      home: https://github.com/dotnet/desktop                                         # [win]
      license: MIT                                                                    # [win]
      license_file: dotnet/LICENSE.txt                                                # [win]
      summary: |                                                                      # [win]
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

about:
  home: https://github.com/dotnet/core
  license: MIT
  license_file: dotnet/LICENSE.txt
  summary: |
    .NET Core is a free and open-source managed computer software
    framework for the Windows, Linux, and macOS operating systems.

extra:
  recipe-maintainers:
    - dhirschfeld
    - ZimmerA
    - acesnik
