{% set sdk_version = "7.0.100" %}
{% set runtime_version = "7.0.0" %}
{% set sha256 = "4f6a1d9bfdcffadaf5deb9c9c30d0c7864c2d0478ec2804e766f3d614fc1e33e" %}  # [win]
{% set platform = "win-x64" %}    # [win]

{% set ext = "tar.gz" %}      # [not win]
{% set ext = "zip" %}         # [win]

package:
  name: dotnet
  version: {{ sdk_version }}

source:
  url: https://dotnetcli.azureedge.net/dotnet/Sdk/{{ sdk_version }}/dotnet-sdk-{{ sdk_version }}-{{ platform }}.{{ ext }}
  sha256: {{ sha256 }}
  folder: dotnet

build:
  number: 0
  binary_relocation: False  
  skip: True # [not win]

outputs:
  - name: dotnet
    version: {{ sdk_version }}
    requirements:
      run:
        - {{ pin_subpackage('dotnet-runtime', exact=True) }}
        - {{ pin_subpackage('dotnet-aspnetcore', exact=True) }}
        - {{ pin_subpackage('dotnet-desktop', exact=True) }}  # [win]
        - {{ pin_subpackage('dotnet-sdk', exact=True) }}
    test:
      commands:
       - dotnet --version

  - name: dotnet-runtime
    version: {{ runtime_version }}
    build:
      binary_relocation: False  
      missing_dso_whitelist: 
          - "*"

    script: build-runtime.bat       # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
    test:
      commands:
        - dotnet --list-runtimes
        - if not defined DOTNET_ROOT exit 1   # [win]
        - if not defined DOTNET_TOOLS exit 1  # [win]
    about:
      home: https://github.com/dotnet/runtime
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-sdk
    version: {{ sdk_version }}
    script: build-sdk.bat       # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
      run:
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - dotnet --version                   # [not aarch64]
    about:
      home: https://github.com/dotnet/sdk
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-aspnetcore
    version: {{ runtime_version }}
    script: build-aspnetcore.bat    # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
      run:
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.AspNetCore.App exit 1  # [win]
    about:
      home: https://github.com/dotnet/aspnetcore
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-desktop                                                              # [win]
    version: {{ runtime_version }}                                                    # [win]
    script: build-desktop.bat                                                         # [win]
    requirements:                                                                     # [win]
      build:                                                                          # [win]
        - posix                                                                       # [win]
      run:                                                                            # [win]
        - dotnet-runtime ={{ runtime_version }}                                       # [win]
    test:                                                                             # [win]
      commands:                                                                       # [win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.WindowsDesktop.App exit 1  # [win]
    about:                                                                            # [win]
      home: https://github.com/dotnet/desktop                                         # [win]
      license: MIT                                                                    # [win]
      license_file: dotnet/LICENSE.txt                                                # [win]
      summary: |                                                                      
        .NET Core is a free and open-source managed computer software                 # [win]
        framework for the Windows, Linux, and macOS operating systems.                # [win]
        .

about:
  home: https://github.com/dotnet/core
  license: MIT
  license_file: dotnet/LICENSE.txt
  summary: |
    .NET Core is a free and open-source managed computer software
    framework for the Windows, Linux, and macOS operating systems.

extra:
  recipe-maintainers:
    - bkreider
