{% set sdk_version = "6.0.300" %}
{% set runtime_version = "6.0.5" %}
{% set sha256 = "20fa1686e9a046b364cf0478bdb560fb39be3a9a2608103b93b7e8c162018359" %}  # [aarch64]
{% set sha256 = "1d4c8c90a5c32de9fc4e9872c79a97271abdff3a60fb55e36690e558d5697005" %}  # [linux]
{% set sha256 = "06379c366336da23ed3441b19163f8ac5bde158d779e2eeb3532e237979d23ca" %}  # [arm64]
{% set sha256 = "25a818367ea4509eb897884548fc5d9b2388fc9f08ab52ea10d3e6eb1effd1ea" %}  # [osx]
{% set sha256 = "e238e0e1579962e5bfc109a33784fb88101b648b358c96740d9c4cd8de8b2fe9" %}  # [win]
{% set platform = "linux-arm64" %}    # [aarch64]
{% set platform = "linux-x64" %}  # [linux]
{% set platform = "osx-arm64" %}  # [arm64]
{% set platform = "osx-x64" %}    # [osx]
{% set platform = "win-x64" %}    # [win]
{% set ext = "tar.gz" %}      # [not win]
{% set ext = "zip" %}         # [win]

package:
  name: dotnet
  version: {{ sdk_version }}

source:
  url: https://dotnetcli.azureedge.net/dotnet/Sdk/{{ sdk_version }}/dotnet-sdk-{{ sdk_version }}-{{ platform }}.{{ ext }}
  sha256: {{ sha256 }}
  folder: dotnet

build:
  number: 0
  binary_relocation: False  # [osx]

outputs:
  - name: dotnet
    version: {{ sdk_version }}
    requirements:
      run:
        - {{ pin_subpackage('dotnet-runtime', exact=True) }}
        - {{ pin_subpackage('dotnet-aspnetcore', exact=True) }}
        - {{ pin_subpackage('dotnet-desktop', exact=True) }}  # [win]
        - {{ pin_subpackage('dotnet-sdk', exact=True) }}
    test:
      commands:
       - dotnet --version

  - name: dotnet-runtime
    version: {{ runtime_version }}
    script: build-runtime.bat       # [win]
    script: build-runtime.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
    test:
      commands:
        - dotnet --list-runtimes
        #- test "${DOTNET_ROOT}" = "${CONDA_PREFIX}/lib/dotnet"         # [unix]
        #- test "${DOTNET_TOOLS}" = "${CONDA_PREFIX}/lib/dotnet/tools"  # [unix]
        #- if not defined DOTNET_ROOT exit 1   # [win]
        #- if not defined DOTNET_TOOLS exit 1  # [win]
    about:
      home: https://github.com/dotnet/runtime
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-sdk
    version: {{ sdk_version }}
    script: build-sdk.bat       # [win]
    script: build-sdk.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust             # [linux64]
        - libcurl               # [unix]
        - icu                   # [unix]
        - krb5                  # [unix]
        - __glibc >=2.17        # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - dotnet --version                   # [not aarch64]
        - test -f $PREFIX/lib/dotnet/dotnet  # [aarch64]
    about:
      home: https://github.com/dotnet/sdk
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-aspnetcore
    version: {{ runtime_version }}
    script: build-aspnetcore.bat    # [win]
    script: build-aspnetcore.sh     # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - test -d $PREFIX/lib/dotnet/shared/Microsoft.AspNetCore.App              # [not win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.AspNetCore.App exit 1  # [win]
    about:
      home: https://github.com/dotnet/aspnetcore
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-desktop                                                              # [win]
    version: {{ runtime_version }}                                                    # [win]
    script: build-desktop.bat                                                         # [win]
    requirements:                                                                     # [win]
      build:                                                                          # [win]
        - posix                                                                       # [win]
      run:                                                                            # [win]
        - dotnet-runtime ={{ runtime_version }}                                       # [win]
    test:                                                                             # [win]
      commands:                                                                       # [win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.WindowsDesktop.App exit 1  # [win]
    about:                                                                            # [win]
      home: https://github.com/dotnet/desktop                                         # [win]
      license: MIT                                                                    # [win]
      license_file: dotnet/LICENSE.txt                                                # [win]
      summary: |                                                                      # [win]
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

about:
  home: https://github.com/dotnet/core
  license: MIT
  license_file: dotnet/LICENSE.txt
  summary: |
    .NET Core is a free and open-source managed computer software
    framework for the Windows, Linux, and macOS operating systems.

extra:
  recipe-maintainers:
    - dhirschfeld
    - ZimmerA
    - acesnik
